export const ActionTypes = {
  SET_DRIVERS: "SET_DRIVERS",
  SELECTED_DRIVER: "SELECTED_DRIVER",
  REMOVE_SELECTED_DRIVER: "REMOVE_SELECTED_DRIVER",
  SET_RIDERS: "SET_RIDERS",
  SELECTED_RIDER: "SELECTED_RIDER",
  REMOVE_SELECTED_RIDER: "REMOVE_SELECTED_RIDER",
};
